### ISSUE TITLE
Main app idea

### ISSUE THREAD

**Issue by dan-koller** [dan-koller/WinPostInstaller#1]
# Idea
The main idea of this app is to provide a simple command line tool to install necessary apps as well as the initial configuration of services (e.g. git). The usage of the end product should be something like this:

- `ExecutableName.exe --gitname "Your Name" --gitmail "your@mail.com"` (with git config)
- `ExecutableName.exe --host "PC-Name"` (with hostname specified)
- `ExecutableName.exe` (Base setup, git profile needs to be configured manually but base config (e.g. autocrlf=true) will be applied)

## Tech stack
- .NET Core 7/C# app due to best compatibility with windows
- `winget` as base technology to install packages
- PowerShell, Batch and/or Bash to run smaller scripts

## Main program flow

1. Set the environment variables (Get the current user, etc)*
2. Set the Hostname**
3. Install winget***
4. Install the selected packages
5. Apply settings and configurations (copy files, etc.)

## Resources

*) See this issue on why this is important: https://github.com/dan-koller/winget-install/issues/10
**) Use the PowerShell command https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/rename-computer?view=powershell-7.3
***) An explanation on how to install Microsoft Store apps via powershell or code: https://serverfault.com/a/1052641
****)An example format for the `packagelist.json`:
`
{
  "Chrome": "winget install -e --id Google.Chrome",
  "Drive": "winget install -e --id Google.Drive"
}
`
*****) Make a multi-selection terminal/console prompt:
- Check this usage example for a bash script: https://gist.github.com/sergiofbsilva/099172ea597657b0d0008dc367946953
- And a suitable library for C#: https://github.com/spectreconsole/spectre.console

## Todos

- [x] Create a basic cli app with .NET
- [x] Add a message to the user to accept UAC popups
- [x] Get the cli arguments
- [x] Set the hostname
- [x] Install winget via code
- [x] ~~Run package installation script~~
- [x] List packages in .txt file as plain strings, read them from file and run every single command as ps command (also add `--accept-eula...` flags)
- [x] Get the exit code from the install script (0 -> move on, 1 -> print the error)
- [x] Copy config files and apply settings
- [x] Prompt the user to reboot the system
- [x] Compile the app to .exe

**Comment by dan-koller** [comment]
Add a shutdown prompt after the script has finished like "Reboot now or later"

**Comment by dan-koller** [comment]
Add a message to the user to accept UAC popups

**Comment by dan-koller** [comment]
Everything's done and fully working app got released!
